// PDF generation via browser print API — no external dependencies needed

export function exportQuotePDF(quote, customer, businessName = 'Arwa Enterprises', taxConfig = {}) {
  const fmt = (n) => `$${(Number(n) || 0).toFixed(2)}`;
  const subtotal = (quote.items || []).reduce((s, i) => s + (i.unitPrice || 0) * (i.qty || 1), 0);
  const taxRate  = quote.taxRate || 0;
  const taxAmt   = subtotal * (taxRate / 100);
  const total    = subtotal + taxAmt;

  const itemRows = (quote.items || []).map(i => `
    <tr>
      <td>${i.name || ''}</td>
      <td>${i.sku || '—'}</td>
      <td style="text-align:center">${i.qty || 1}</td>
      <td style="text-align:right">${fmt(i.unitPrice)}</td>
      <td style="text-align:right">${fmt((i.unitPrice || 0) * (i.qty || 1))}</td>
    </tr>`).join('');

  const html = `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8"/>
<title>Quote ${quote.quoteNumber}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; font-size: 13px; color: #1a1a2e; padding: 40px; }
  .header { display: flex; justify-content: space-between; align-items: flex-start; margin-bottom: 36px; border-bottom: 3px solid #4F46E5; padding-bottom: 24px; }
  .brand h1 { font-size: 24px; font-weight: 900; color: #4F46E5; }
  .brand p  { font-size: 12px; color: #666; margin-top: 4px; }
  .quote-meta { text-align: right; }
  .quote-meta h2 { font-size: 20px; font-weight: 800; color: #1a1a2e; }
  .quote-meta .num { font-size: 15px; font-weight: 700; color: #4F46E5; margin: 4px 0; }
  .quote-meta p  { font-size: 12px; color: #666; }
  .parties { display: flex; gap: 40px; margin-bottom: 28px; }
  .party h4 { font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .06em; color: #888; margin-bottom: 6px; }
  .party p  { font-size: 13px; line-height: 1.6; }
  table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
  thead th { background: #4F46E5; color: #fff; padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: .05em; }
  tbody td { padding: 10px 12px; border-bottom: 1px solid #e5e7eb; font-size: 13px; }
  tbody tr:nth-child(even) td { background: #f9fafb; }
  .totals { margin-left: auto; width: 260px; }
  .totals table { margin-bottom: 0; }
  .totals td { padding: 6px 12px; border: none; }
  .totals .grand td { font-weight: 900; font-size: 15px; border-top: 2px solid #4F46E5; color: #4F46E5; }
  .status-badge { display: inline-block; padding: 3px 10px; border-radius: 20px; font-size: 11px; font-weight: 700; text-transform: uppercase; letter-spacing: .06em; background: #EEF2FF; color: #4F46E5; margin-left: 8px; }
  .notes { margin-top: 28px; padding: 14px; background: #f9fafb; border-left: 4px solid #4F46E5; border-radius: 4px; }
  .notes h4 { font-size: 11px; text-transform: uppercase; letter-spacing: .06em; color: #888; margin-bottom: 6px; }
  .footer { margin-top: 36px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style>
</head>
<body>
<div class="header">
  <div class="brand">
    <h1>${businessName}</h1>
    <p>${taxConfig.gstNumber ? 'GST/HST: ' + taxConfig.gstNumber : ''}</p>
  </div>
  <div class="quote-meta">
    <h2>QUOTE <span class="status-badge">${(quote.status || 'draft').toUpperCase()}</span></h2>
    <div class="num">${quote.quoteNumber || 'QT-0001'}</div>
    <p>Date: ${new Date(quote.createdAt || Date.now()).toLocaleDateString('en-CA')}</p>
    <p>Valid until: ${quote.validUntil ? new Date(quote.validUntil).toLocaleDateString('en-CA') : '—'}</p>
  </div>
</div>

<div class="parties">
  <div class="party">
    <h4>From</h4>
    <p><strong>${businessName}</strong></p>
  </div>
  <div class="party">
    <h4>Bill To</h4>
    <p><strong>${customer?.name || quote.customerName || '—'}</strong><br/>
    ${customer?.email ? customer.email + '<br/>' : ''}
    ${customer?.phone || ''}</p>
  </div>
</div>

<table>
  <thead>
    <tr>
      <th>Product</th><th>SKU</th><th style="text-align:center">Qty</th>
      <th style="text-align:right">Unit Price</th><th style="text-align:right">Total</th>
    </tr>
  </thead>
  <tbody>${itemRows || '<tr><td colspan="5" style="text-align:center;color:#999">No items</td></tr>'}</tbody>
</table>

<div class="totals">
  <table>
    <tr><td>Subtotal</td><td style="text-align:right">${fmt(subtotal)}</td></tr>
    ${taxRate > 0 ? `<tr><td>Tax (${taxRate}%)</td><td style="text-align:right">${fmt(taxAmt)}</td></tr>` : ''}
    <tr class="grand"><td>Total</td><td style="text-align:right">${fmt(total)}</td></tr>
  </table>
</div>

${quote.notes ? `<div class="notes"><h4>Notes</h4><p>${quote.notes}</p></div>` : ''}

<div class="footer">
  This quote was generated by ${businessName} · ${new Date().toLocaleDateString('en-CA')} · Powered by Arwa 1.0
</div>

<script>window.onload = () => { window.print(); }</script>
</body>
</html>`;

  const win = window.open('', '_blank', 'width=900,height=700');
  if (win) {
    win.document.write(html);
    win.document.close();
  }
}
